### ISSUE TITLE
想问一下能不能sort by players or albums

### ISSUE THREAD

**Issue by dzzhang96** [yuetsin/ncm-playlist-sorter#3]
谢谢！

**Comment by yuetsin** [comment]
尝试在 [e2f86dc](https://github.com/yuetsin/ncm-playlist-sorter/commit/e2f86dc282e9d06071987e347a2642938f22f601) 加上了。

---

对于多位艺术家合作的歌曲，不同客户端显示效果略有不同。

这里模仿 macOS 客户端的拼接方式，用两边带空格的半角斜杠（` / `）连接。

如果显示效果不好的话，可以试试修改[这里](https://github.com/yuetsin/ncm-playlist-sorter/blob/e2f86dc282e9d06071987e347a2642938f22f601/src/sorter.py#L98)的拼接字符串。

**Comment by dzzhang96** [comment]
> 尝试在 [e2f86dc](https://github.com/yuetsin/ncm-playlist-sorter/commit/e2f86dc282e9d06071987e347a2642938f22f601) 加上了。
> 
> 对于多位艺术家合作的歌曲，不同客户端显示效果略有不同。
> 
> 这里模仿 macOS 客户端的拼接方式，用两边带空格的半角斜杠（`/`）连接。
> 
> 如果显示效果不好的话，可以试试修改[这里](https://github.com/yuetsin/ncm-playlist-sorter/blob/e2f86dc282e9d06071987e347a2642938f22f601/src/sorter.py#L98)的拼接字符串。

十分感谢您的代码！测试发现新增的三种排序方式只能处理10首歌，请问您这边是这样吗？

**Comment by yuetsin** [comment]
现在，服务器在未登录状态下只提供 10 首歌曲的详情。

42cb6f5 跟随服务端的变更，会以[每秒 100 首歌](https://github.com/yuetsin/ncm-playlist-sorter/blob/35d4d93d1fe211d5e81cf29a1f45cb1f09c2a1de/src/sorter.py#L24)的速率请求完全部数据。

希望这样可以解决问题（

**Comment by dzzhang96** [comment]
成功了！！蟹蟹！！可太开心了！！
